[server]
headless = false
port = 8502
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#F0F4F8"
secondaryBackgroundColor = "#E3F2FD"
textColor = "#1A237E"
font = "sans serif"
base = "light"
